# Generated by Django 2.1.5 on 2019-05-19 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('initials', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ManyToManyField(related_name='professors', to='survey.Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='survey.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='survey.Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='survey.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='survey.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='survey.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.UUIDField(default=uuid.uuid4)),
                ('submitted', models.BooleanField(default=False)),
                ('submit_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='survey.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudyOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='survey.Study')),
            ],
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='survey.Study'),
        ),
        migrations.AddField(
            model_name='question',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='survey.Study'),
        ),
        migrations.AddField(
            model_name='question',
            name='study_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='survey.StudyOption'),
        ),
        migrations.AddField(
            model_name='class',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='survey.Program'),
        ),
        migrations.AddField(
            model_name='answer',
            name='questions',
            field=models.ManyToManyField(related_name='answers', to='survey.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='studyoption',
            unique_together={('study', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student', 'study', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('study', 'study_option', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('name', 'institution')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('value', 'text')},
        ),
    ]
