# Generated by Django 2.1.5 on 2019-05-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='type',
            new_name='acronym',
        ),
    ]
