insert into survey_institution (name, initials) values ('Universidade Federal de São Paulo', 'Unifesp');
insert into survey_program (name, institution_id) select 'Bacharelado em Ciência da Computação', id from survey_institution where initials = 'Unifesp';
insert into survey_class (code, description, semester, year, program_id) select 'IA', 'Integral A', 1, 2019, id from survey_program where name = 'Bacharelado em Ciência da Computação';
insert into survey_class (code, description, semester, year, program_id) select 'IB', 'Integral B', 1, 2019, id from survey_program where name = 'Bacharelado em Ciência da Computação';
insert into survey_class (code, description, semester, year, program_id) select 'NA', 'Noturno A', 1, 2019, id from survey_program where name = 'Bacharelado em Ciência da Computação';
insert into auth_user (password, is_superuser, username, first_name, email, is_staff, is_active, date_joined, last_name) values ('pbkdf2_sha256$120000$AQVEf6zPZljK$y12fUxd3RrlYoKMYK4C0mKsSkQjHUDsRFjgVqxygy4M=', false, 'student1', 'Student1FN', 's1@ggmail.com', false, true, DateTime('now'), 'Student1LN');
insert into auth_user (password, is_superuser, username, first_name, email, is_staff, is_active, date_joined, last_name) values ('pbkdf2_sha256$120000$AQVEf6zPZljK$y12fUxd3RrlYoKMYK4C0mKsSkQjHUDsRFjgVqxygy4M=', false, 'student2', 'Student2FN', 's2@ggmail.com', false, true, DateTime('now'), 'Student2LN');
insert into auth_user (password, is_superuser, username, first_name, email, is_staff, is_active, date_joined, last_name) values ('pbkdf2_sha256$120000$AQVEf6zPZljK$y12fUxd3RrlYoKMYK4C0mKsSkQjHUDsRFjgVqxygy4M=', false, 'professor1', 'Professor1FN', 'p1@ggmail.com', false, true, DateTime('now'), 'Professor1LN');
insert into auth_user (password, is_superuser, username, first_name, email, is_staff, is_active, date_joined, last_name) values ('pbkdf2_sha256$120000$AQVEf6zPZljK$y12fUxd3RrlYoKMYK4C0mKsSkQjHUDsRFjgVqxygy4M=', true, 'admin1', 'Admin1FN', 'admin@ggmail.com', true, true, DateTime('now'), 'Admin1LN');
insert into survey_student (user_id, sclass_id) select (select id from auth_user where username = 'student1'), id from survey_class where code = 'IA';
insert into survey_student (user_id, sclass_id) select (select id from auth_user where username = 'student2'), id from survey_class where code = 'NA';
insert into survey_professor (user_id) select (select id from auth_user where username = 'professor1');
insert into auth_group (name) values ('Professor'), ('Student');
insert into auth_user_groups(user_id, group_id) select (select id from auth_user where username = 'student1'), id from auth_group where name = 'Student';
insert into auth_user_groups(user_id, group_id) select (select id from auth_user where username = 'student2'), id from auth_group where name = 'Student';
insert into auth_user_groups(user_id, group_id) select (select id from auth_user where username = 'professor1'), id from auth_group where name = 'Professor';
insert into survey_study (acronym, description) values ('IM', 'Inteligências Múltiplas');
insert into survey_study (acronym, description) values ('EA', 'Estilos de Aprendizagem');
insert into survey_studyoption (code, description, study_id) select 'ATIVO', 'Ativo', id from survey_study where acronym = 'EA';
insert into survey_studyoption (code, description, study_id) select 'REFLEXIVO', 'Reflexivo', id from survey_study where acronym = 'EA';
insert into survey_studyoption (code, description, study_id) select 'TEORICO', 'Teórico', id from survey_study where acronym = 'EA';
insert into survey_studyoption (code, description, study_id) select 'PRAGMATICO', 'Pragmático', id from survey_study where acronym = 'EA';
insert into survey_studyoption (code, description, study_id) select 'VERBAL_LINGUISTICA', 'Verbal-Linguística', id from survey_study where acronym = 'IM';
insert into survey_studyoption (code, description, study_id) select 'LOGICA_MATEMATICA', 'Lógica-Matemática', id from survey_study where acronym = 'IM';
insert into survey_studyoption (code, description, study_id) select 'VISUAL_ESPACIAL', 'Visual-Espacial', id from survey_study where acronym = 'IM';
insert into survey_studyoption (code, description, study_id) select 'INTERPESSOAL', 'Interpessoal', id from survey_study where acronym = 'IM';
insert into survey_studyoption (code, description, study_id) select 'CINESTESICA_CORPORAL', 'Cinestésica-corporal', id from survey_study where acronym = 'IM';
insert into survey_studyoption (code, description, study_id) select 'RITMICA_MUSICAL', 'Rítmica-musical', id from survey_study where acronym = 'IM';
insert into survey_studyoption (code, description, study_id) select 'INTRAPESSOAL', 'Intrapessoal', id from survey_study where acronym = 'IM';
insert into survey_studyoption (code, description, study_id) select 'NATURALISTA', 'Naturalista', id from survey_study where acronym = 'IM';
insert into survey_question (position, text, study_id, study_option_id) select 1, 'pergunta 1 IM', id, (select id from survey_studyoption where code = 'VERBAL_LINGUISTICA') from survey_study where acronym = 'IM';
insert into survey_question (position, text, study_id, study_option_id) select 2, 'pergunta 2 IM', id, (select id from survey_studyoption where code = 'VERBAL_LINGUISTICA') from survey_study where acronym = 'IM';
insert into survey_question (position, text, study_id, study_option_id) select 3, 'pergunta 3 IM', id, (select id from survey_studyoption where code = 'INTERPESSOAL') from survey_study where acronym = 'IM';
insert into survey_question (position, text, study_id, study_option_id) select 4, 'pergunta 4 IM', id, (select id from survey_studyoption where code = 'INTERPESSOAL') from survey_study where acronym = 'IM';
insert into survey_question (position, text, study_id, study_option_id) select 1, 'pergunta 1 EA', id, (select id from survey_studyoption where code = 'ATIVO') from survey_study where acronym = 'EA';
insert into survey_question (position, text, study_id, study_option_id) select 2, 'pergunta 2 EA', id, (select id from survey_studyoption where code = 'ATIVO') from survey_study where acronym = 'EA';
insert into survey_question (position, text, study_id, study_option_id) select 3, 'pergunta 3 EA', id, (select id from survey_studyoption where code = 'TEORICO') from survey_study where acronym = 'EA';
insert into survey_question (position, text, study_id, study_option_id) select 4, 'pergunta 4 EA', id, (select id from survey_studyoption where code = 'TEORICO') from survey_study where acronym = 'EA';
insert into survey_answer (value, text) values (0, 'Nunca se aplica a mim');
insert into survey_answer (value, text) values (1, 'Aplica-se raramente a mim');
insert into survey_answer (value, text) values (2, 'Aplica-se muitas vezes a mim');
insert into survey_answer (value, text) values (3, 'Aplica-se sempre a mim');
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 1 IM') from survey_answer where value = 0;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 2 IM') from survey_answer where value = 0;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 3 IM') from survey_answer where value = 0;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 4 IM') from survey_answer where value = 0;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 1 EA') from survey_answer where value = 0;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 2 EA') from survey_answer where value = 0;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 3 EA') from survey_answer where value = 0;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 4 EA') from survey_answer where value = 0;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 1 IM') from survey_answer where value = 1;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 2 IM') from survey_answer where value = 1;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 3 IM') from survey_answer where value = 1;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 4 IM') from survey_answer where value = 1;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 1 EA') from survey_answer where value = 1;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 2 EA') from survey_answer where value = 1;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 3 EA') from survey_answer where value = 1;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 4 EA') from survey_answer where value = 1;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 1 IM') from survey_answer where value = 2;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 2 IM') from survey_answer where value = 2;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 3 IM') from survey_answer where value = 2;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 4 IM') from survey_answer where value = 2;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 1 EA') from survey_answer where value = 2;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 2 EA') from survey_answer where value = 2;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 3 EA') from survey_answer where value = 2;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 4 EA') from survey_answer where value = 2;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 1 IM') from survey_answer where value = 3;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 2 IM') from survey_answer where value = 3;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 3 IM') from survey_answer where value = 3;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 4 IM') from survey_answer where value = 3;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 1 EA') from survey_answer where value = 3;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 2 EA') from survey_answer where value = 3;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 3 EA') from survey_answer where value = 3;
insert into  survey_answer_questions (answer_id, question_id) select id, (select id from survey_question where text = 'pergunta 4 EA') from survey_answer where value = 3;
insert into  survey_professor_classes (class_id, professor_id) select id, (select id from survey_professor where user_id in (select id from auth_user where username = 'professor1')) from survey_class;
