# Generated by Django 2.1.5 on 2019-05-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190520_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswerlog',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentAnswerLog',
        ),
    ]
