# Generated by Django 2.2.4 on 2019-08-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190809_0709'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('program', 'code', 'year', 'semester')},
        ),
    ]
