# Generated by Django 2.2.4 on 2019-08-17 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190813_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Semestre 1 é o menor valor possível'), django.core.validators.MaxValueValidator(2, 'Semestre 2 é o maior valor possível')]),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2018, '2018 é o menor ano passado suportado'), django.core.validators.MaxValueValidator(2050, '2050 é o maior ano futuro suportado')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'A posição da questão precisa ser maior que zero')]),
        ),
    ]
