# Generated by Django 2.1.9 on 2019-06-20 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190619_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_datetime', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answer_logs', to='survey.Student')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answer_logs', to='survey.Study')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentanswerlog',
            unique_together={('student', 'study')},
        ),
    ]
