# Generated by Django 2.2.20 on 2021-05-11 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190817_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='programs',
            field=models.ManyToManyField(related_name='professors', to='survey.Program'),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Semestre %(limit_value) é o menor valor possível'), django.core.validators.MaxValueValidator(2, 'Semestre %(limit_value) é o maior valor possível')]),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2018, '%(limit_value) é o menor ano passado suportado'), django.core.validators.MaxValueValidator(2050, '%(limit_value) é o maior ano futuro suportado')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'A posição da questão precisa ser maior ou igual a %(limit_value)')]),
        ),
    ]
